name: Run ESG Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Download model
        run: |
          mkdir -p model
          wget https://github.com/<USERNAME>/<REPO>/releases/download/<TAG>/esg_total_score_model.keras -O model/esg_total_score_model.keras

      - name: Run inference
        run: python src/inference.py

      - name: Verify predictions
        run: |
          if [ -f predictions.csv ]; then
            echo "predictions.csv created successfully!"
          else
            echo "ERROR: predictions.csv not found!"
            exit 1
          fi

      - name: Upload predictions
        uses: actions/upload-artifact@v4
        with:
          name: predictions
          path: predictions.csv
