name: ESG Pipeline CI/CD

on:
  push:
    branches: [ main ]   # runs when you push to main
  pull_request:
    branches: [ main ]   # also runs on PRs

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Notebook/Script
      run: |
        # If using a notebook
        pip install nbconvert
        jupyter nbconvert --to notebook --execute ESG_Prediction.ipynb --output executed_notebook.ipynb
        
        # OR if using Python scripts
        # python train.py
