name: Run ESG Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run inference script
        run: python src/inference.py

      - name: Upload predictions
        uses: actions/upload-artifact@v3
        with:
          name: predictions
          path: predictions.csv
